apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::240415474545:role/eksctl-eksctl-demo-nodegroup-ng-2-NodeInstanceRole-QDYXEQ4XIDGF
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::240415474545:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-09T09:42:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1889"
  uid: 837ca9f5-e4ec-4b38-82d7-f5e47f9a3597
